### ISSUE TITLE
Allow for word filtering

### ISSUE THREAD

**Issue by HyperCrowd** [HyperCrowd/word-cluster-matrix#3]
When feeding sentences into a field, allow for conditional filtering or either accept or reject a sentence based on custom conditions involving word presence.

**Comment by softcookiepp** [comment]
hi I can do this if you want c:

**Comment by softcookiepp** [comment]
Just for clarification, do you want it to be able to modify the sentences themselves to exclude words? Or do you just want to be able to discard any sentences that do not meet certain criteria? Or both?

**Comment by HyperCrowd** [comment]
Here we remove stop words: https://github.com/HyperCrowd/word-cluster-matrix/blob/main/grammarField.js#L56

After that, we singularize words here: https://github.com/HyperCrowd/word-cluster-matrix/blob/main/grammarField.js#L64

This is the line where additional filtering of individual words go: https://github.com/HyperCrowd/word-cluster-matrix/blob/main/grammarField.js#L65

We would exclude custom tokens and still keep the sentences

**Comment by softcookiepp** [comment]
Alright, its finished now. https://github.com/HyperCrowd/word-cluster-matrix/commit/3aa62658157d378b526a26d0f595d2535a744601
